### ISSUE TITLE
Create catch blocks which allow the application to keep running in case of error

### ISSUE THREAD

**Issue by lkitto** [gastate/DALN#10]
Currently error result in the application exiting.  However if the application is to run as a batch process, errors will need to be logged and the application will need to keep running the batch.  
- This could be handled later depending on the batch implementation.

**Comment by ShakibAhmed** [comment]
On next commit, the program will continue to run after errors except if the post already exists in the database. Otherwise, multiple entries may be made for one post.

**Comment by lkitto** [comment]
You will need to make this change because there are occasions when the post exists but not all of the media associated with the post has been uploaded.  How will you upload the missing media if the application exits?

Lisa Kitto
Application Developer
Strategic Innovation & Development
Office of Instructional Innovation & Technology
GSU:

(404) 413-4392tel:(404)%20413-4392

GPC:

(678) 891-3466tel:(678)%20891-3466

Email:

 lkitto@gsu.edumailto:lkitto@gsu.edu

**Comment by ShakibAhmed** [comment]
Which method is preferred: Allowing multiple entries of the same DALN post in the DB (you just manually delete the bad one), or rewriting the same entry? The first method has an easier implementation while the second will take more work.

**Comment by lkitto** [comment]
Neither.
1. ```
     look at the db to see if the post exists
   ```
2. ```
     If the post exists query to see if any of the media is missing (missing media attribute)
   ```
3. ```
     If so, load the media
   ```
4. ```
     If not, return
   ```

Lisa Kitto
Application Developer
Strategic Innovation & Development
Office of Instructional Innovation & Technology
GSU:

(404) 413-4392tel:(404)%20413-4392

GPC:

(678) 891-3466tel:(678)%20891-3466

Email:

 lkitto@gsu.edumailto:lkitto@gsu.edu
