### ISSUE TITLE
Implement Error logging with additional attribute denoting if all media is present

### ISSUE THREAD

**Issue by lkitto** [gastate/DALN#6]
Currently the upload process checks if a post exists in the DB and if it exists exists the upload process.  However, this creates a problem is an error happens during upload preventing the entire post from being recorded.

When a file is uploaded it created a DB entry and stores media in appropriate CDN.  Should the media storage fail, the DB entry should be deleted.  This will prevent the post from being bypassed by the "exists" check at the beginning of the upload process and allow for re-upload.

**Comment by ShakibAhmed** [comment]
Just wanted some clarification about how to approach this. 
For example, if a post has 3 files: a text file, a video file, and an audio file, and an upload is attempted. The text and the audio are successfully uploaded, but the video upload fails, so the entry from the DB is either never created or deleted. Should the uploaded text file and audio (which will both now exist on the CDNs) be deleted as well automatically?

**Comment by lkitto** [comment]
If any of the media fails to upload on a post the post should not be in the database.  So, if you create the database entry first, it must be deleted.  If you create the database entry last, it should not be recorded.  The point her is that is the existence of a record in the database prevents the media from being uploaded, then the records needs to not exist.  Because otherwise, how will you reload the media?

Meaning, if any part of the upload process fails, all media/metadata/db records must be deleted.  It should be as if it never happened.  Make sense?
This is documentation specific to JDBC, but it should help clarify the concept.
https://docs.oracle.com/javase/tutorial/jdbc/basics/transactions.html

Lisa Kitto
Application Developer
Strategic Innovation & Development
Office of Instructional Innovation & Technology
GSU:

(404) 413-4392tel:(404)%20413-4392

GPC:

(678) 891-3466tel:(678)%20891-3466

Email:

 lkitto@gsu.edumailto:lkitto@gsu.edu

**Comment by ShakibAhmed** [comment]
Based on input from Jaro, a new attribute is added in the DB that states whether all the posts' assets were uploaded. The program checks all file locations for a post and if any are null, the attribute is set to false. The entry isn't deleted, but you can check the table for posts that need to be re-uploaded.

**Comment by lkitto** [comment]
The main idea is just to ensure that all media related to the post is upload, so that works.

Lisa Kitto
Application Developer
Strategic Innovation & Development
Office of Instructional Innovation & Technology
GSU:

(404) 413-4392tel:(404)%20413-4392

GPC:

(678) 891-3466tel:(678)%20891-3466

Email:

 lkitto@gsu.edumailto:lkitto@gsu.edu
