### ISSUE TITLE
Check Video Upload to SPROUT to ensure functioning as intended

### ISSUE THREAD

**Issue by lkitto** [gastate/DALN#8]
During tests the video upload failed.  Stack trace indicates some security issue.  Perhaps so configuration is missing.
[54-full-log_Stacktrace.txt](https://github.com/gastate/DALN/files/450390/54-full-log_Stacktrace.txt)

**Comment by ShakibAhmed** [comment]
I believe the cause is that the keystore on your machine does not contain a trust certificate for SproutVideo (I remember getting the same error and adding it manually). Will look into a way to include this with other configuration

**Comment by lkitto** [comment]
Do you want to export the key and send it to me?

Lisa Kitto
Application Developer
Strategic Innovation & Development
Office of Instructional Innovation & Technology
GSU:

(404) 413-4392tel:(404)%20413-4392

GPC:

(678) 891-3466tel:(678)%20891-3466

Email:

 lkitto@gsu.edumailto:lkitto@gsu.edu

**Comment by ShakibAhmed** [comment]
I attached the certificate for SproutVideo. I used this command to import the certificate, but it will likely be different if you aren't using Windows.

`keytool -import -alias sproutvideo -keystore %Path to cacerts file% -file %Path to SproutVideo certificate%`

My cacerts file was located at
`C:\Program Files (x86)\Java\jdk1.7.0_25\jre\lib\security\cacerts`

[sproutvideoCert.zip](https://github.com/gastate/DALN/files/450593/sproutvideoCert.zip)

**Comment by lkitto** [comment]
Don’t see the attachment.

Lisa Kitto
Application Developer
Strategic Innovation & Development
Office of Instructional Innovation & Technology
GSU:

(404) 413-4392tel:(404)%20413-4392

GPC:

(678) 891-3466tel:(678)%20891-3466

Email:

 lkitto@gsu.edumailto:lkitto@gsu.edu

**Comment by ShakibAhmed** [comment]
I'll email it instead.

**Comment by lkitto** [comment]
I thought you meant that you attached it to the email.

Lisa Kitto
Application Developer
Strategic Innovation & Development
Office of Instructional Innovation & Technology
GSU:

(404) 413-4392tel:(404)%20413-4392

GPC:

(678) 891-3466tel:(678)%20891-3466

Email:

 lkitto@gsu.edumailto:lkitto@gsu.edu

**Comment by lkitto** [comment]
I got it.

Lisa Kitto
Application Developer
Strategic Innovation & Development
Office of Instructional Innovation & Technology
GSU:

(404) 413-4392tel:(404)%20413-4392

GPC:

(678) 891-3466tel:(678)%20891-3466

Email:

 lkitto@gsu.edumailto:lkitto@gsu.edu
