### ISSUE TITLE
Fix Soudcloud bug

### ISSUE THREAD

**Issue by lkitto** [gastate/DALN#9]
[Other SoundClod Error.txt](https://github.com/gastate/DALN/files/482716/Other.SoundClod.Error.txt)
[SoundCloud Error.txt](https://github.com/gastate/DALN/files/482715/SoundCloud.Error.txt)

**Comment by ShakibAhmed** [comment]
Can you recreate the error and identify under which conditions that occurs?
I tried reproducing the error on my computer but I couldn't get anything.

**Comment by lkitto** [comment]
This is the error that we discussed yesterday about the soundcloud not recognizing the file is available for upload.

**Comment by lkitto** [comment]
Fix the path so that it uses the correct slashes

**Comment by jaroklc-gsu** [comment]
http://stackoverflow.com/questions/31633912/how-to-wait-for-async-actions-inside-aws-lambda
